name: CD

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: action/checkout@v2
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
           cd /home/mi/app/service-base64
           git pull origin master
           git status
           npm install
           pm2 restart test
